# Generated by Django 2.2.28 on 2023-06-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_xnjui'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fhhj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjuu', models.BigIntegerField()),
            ],
        ),
    ]
